license:
  name: lgpl
  version: 3
program:
  name: Evaluation-Tseytin
  description: Program for the evaluation of the Tseytin transformation.
  authors: Elias Kuiter
  url: https://github.com/ekuiter/evaluation-tseytin
  year: 2021
